name: Deploy Node.js to Azure Web App

on:
  push:
    tags:
    - 'azuredeploy*'

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Print stuff
      run: |
        echo $GITHUB_REF
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install
      run: |
        npm install
    - name: Zip files
      run: |
        zip -r app.zip . -x ".git/*" ".github/*"
    # - name: 'Deploy to Azure WebApp'
    #   uses: azure/webapps-deploy@v2
    #   with: 
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      env:
        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}
      with:
        inlineScript: |
          az webapp deployment source config-zip --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --src app.zip